package bdagenda;
// Generated 17-nov-2019 22:56:44 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tareas generated by hbm2java
 */
@Entity
@Table(name="tareas"
    ,catalog="bdagenda"
)
public class Tareas  implements java.io.Serializable {


     private Integer codigo;
     private Date fecha;
     private String descripcion;
     private Boolean completada;

    public Tareas() {
    }

    public Tareas(Date fecha, String descripcion, Boolean completada) {
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.completada = completada;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="codigo", unique=true, nullable=false)
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="descripcion", length=40)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="completada")
    public Boolean getCompletada() {
        return this.completada;
    }
    
    public void setCompletada(Boolean completada) {
        this.completada = completada;
    }




}


