package bdtelefood;
// Generated 20-nov-2019 9:12:38 by Hibernate Tools 4.3.1



/**
 * EmailsId generated by hbm2java
 */
public class EmailsId  implements java.io.Serializable {


     private String idtienda;
     private String email;

    public EmailsId() {
    }

    public EmailsId(String idtienda, String email) {
       this.idtienda = idtienda;
       this.email = email;
    }
   
    public String getIdtienda() {
        return this.idtienda;
    }
    
    public void setIdtienda(String idtienda) {
        this.idtienda = idtienda;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmailsId) ) return false;
		 EmailsId castOther = ( EmailsId ) other; 
         
		 return ( (this.getIdtienda()==castOther.getIdtienda()) || ( this.getIdtienda()!=null && castOther.getIdtienda()!=null && this.getIdtienda().equals(castOther.getIdtienda()) ) )
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdtienda() == null ? 0 : this.getIdtienda().hashCode() );
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         return result;
   }   


}


