package bdseriestv;
// Generated 16-nov-2019 2:48:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Series generated by hbm2java
 */
public class Series  implements java.io.Serializable {


     private Integer codigo;
     private Cadenastv cadenastv;
     private String titulo;
     private int duracion;
     private Set actoreses = new HashSet(0);

    public Series() {
    }

	
    public Series(int duracion) {
        this.duracion = duracion;
    }
    public Series(Cadenastv cadenastv, String titulo, int duracion, Set actoreses) {
       this.cadenastv = cadenastv;
       this.titulo = titulo;
       this.duracion = duracion;
       this.actoreses = actoreses;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Cadenastv getCadenastv() {
        return this.cadenastv;
    }
    
    public void setCadenastv(Cadenastv cadenastv) {
        this.cadenastv = cadenastv;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }
    public Set getActoreses() {
        return this.actoreses;
    }
    
    public void setActoreses(Set actoreses) {
        this.actoreses = actoreses;
    }




}


