package bdseriestv;
// Generated 15-nov-2019 8:58:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cadenastv generated by hbm2java
 */
public class Cadenastv  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private Set serieses = new HashSet(0);

    public Cadenastv() {
    }

	
    public Cadenastv(String codigo) {
        this.codigo = codigo;
    }
    public Cadenastv(String codigo, String nombre, Set serieses) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.serieses = serieses;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getSerieses() {
        return this.serieses;
    }
    
    public void setSerieses(Set serieses) {
        this.serieses = serieses;
    }




}


