package bdseries;
// Generated 08-nov-2019 8:20:30 by Hibernate Tools 4.3.1



/**
 * Series generated by hbm2java
 */
public class Series  implements java.io.Serializable {


     private Integer codigo;
     private String titulo;
     private String tv;
     private int duracion;

    public Series() {
    }

	
    public Series(int duracion) {
        this.duracion = duracion;
    }
    public Series(String titulo, String tv, int duracion) {
       this.titulo = titulo;
       this.tv = tv;
       this.duracion = duracion;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getTv() {
        return this.tv;
    }
    
    public void setTv(String tv) {
        this.tv = tv;
    }
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }




}


