package bdAnotaciones;
// Generated 15-nov-2019 8:31:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Libros generated by hbm2java
 */
@Entity
@Table(name="libros"
    ,catalog="bdanotaciones"
)
public class Libros  implements java.io.Serializable {


     private int id;
     private String titulo;

    public Libros() {
    }

	
    public Libros(int id) {
        this.id = id;
    }
    public Libros(int id, String titulo) {
       this.id = id;
       this.titulo = titulo;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="titulo", length=60)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }




}


