package bibliotecah;
// Generated 07-nov-2019 8:35:54 by Hibernate Tools 4.3.1



/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private int id;
     private String titulo;
     private String autor;

    public Libros() {
    }

	
    public Libros(int id) {
        this.id = id;
    }
    public Libros(int id, String titulo, String autor) {
       this.id = id;
       this.titulo = titulo;
       this.autor = autor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }




}


