package bibliotecah3;
// Generated 11-nov-2019 8:25:33 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Libros generated by hbm2java
 */
public class Libros  implements java.io.Serializable {


     private int id;
     private String titulo;
     private Set autoreses = new HashSet(0);

    public Libros() {
    }

	
    public Libros(int id) {
        this.id = id;
    }
    public Libros(int id, String titulo, Set autoreses) {
       this.id = id;
       this.titulo = titulo;
       this.autoreses = autoreses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Set getAutoreses() {
        return this.autoreses;
    }
    
    public void setAutoreses(Set autoreses) {
        this.autoreses = autoreses;
    }




}


