package bdtelefood;
// Generated 20-nov-2019 9:12:38 by Hibernate Tools 4.3.1



/**
 * Emails generated by hbm2java
 */
public class Emails  implements java.io.Serializable {


     private EmailsId id;
     private Tiendas tiendas;

    public Emails() {
    }

    public Emails(EmailsId id, Tiendas tiendas) {
       this.id = id;
       this.tiendas = tiendas;
    }
   
    public EmailsId getId() {
        return this.id;
    }
    
    public void setId(EmailsId id) {
        this.id = id;
    }
    public Tiendas getTiendas() {
        return this.tiendas;
    }
    
    public void setTiendas(Tiendas tiendas) {
        this.tiendas = tiendas;
    }




}


